baseURL = "https://sofuck.top"
languageCode = "en-us"
defaultContentLanguage = "zh"
title = "BlackReaper 的友情链接"

googleAnalytics = "UA-131035751-1"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "So Serious"		#名字
	description = "Do your best."	#描述
	avatar = "/img/avatar.png"	#头像
	motto = "Do your best."		#座右铭
	enableToc = true
	enableShareCard = true

	favicon = "/img/PY-Blog.ico"	#博客图标

  #Background settings
	enableColorBG= true		#随机颜色-背景

	#Post-displaying Settings
	#enableTags = true
	#enableCategories = true

  #Cards shown per page
  itemsPerPage = 4

  #Enable card view
  contentType = "cards"

  #Enable Twitter Emoji
  twitterEmoji=true

[social]
	email = "ReaperOfBlack@gmail.com"
	github = "SoGhost"
	stackoverflow = ""
	medium = ""
	twitter = "" 
	siteStartYear = 2018
