baseURL = ""
languageCode = "en-us"
defaultContentLanguage = "zh"
title = "PY->Blog"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "So Serious"

googleAnalytics = "UA-131035751-1"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji = true

[params]
	author = "So Serious"		#名字
	description = "Do your best."	#描述
	avatar = "/img/avatar.png"	#头像
	motto = "Do your best."		#座右铭
	enableToc = true
	enableShareCard = true

	favicon = "/img/PY-Blog.ico"	#博客图标

  	#Background settings
	enableColorBG= true		#随机颜色-背景
	bgBlur = "0px"
	#bgList = ["/img/bg1.jpeg", "/img/bg2.jpg"] 
	bgImage = "/img/bg1.jpeg"	#背景图

	#Post-displaying Settings
	enableTags = true
	enableCategories = true
	
	#Cards or posts shown per page
	itemsPerPage = 4
	
	#Set whether you're hosting "cards" or "posts"
	contentType = "posts"
	
	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = "ReaperOfBlack@gmail.com"
	github = "SoGhost"
    	stackoverflow = ""
	medium = ""
	twitter = "" 
	siteStartYear = 2018
